'use strict';
(() => {
  const $ = (selector) => document.querySelector(selector);
  const $$ = (selector) => [...document.querySelectorAll(selector)];
  const colors = {cyan: '#37cee9', amber: '#ffbd35', text: '#bfd0e5', grid: '#20303f', muted: '#778ea8'};
  const modelNames = {raw_trade_volume: 'Volume proxy', open_interest: 'Open interest', directionalized_trade_volume: 'Directionalized volume'};
  const capabilityStorageKey = `gex.wind-tunnel.capability:${location.origin}`;
  const launchCapability = new URLSearchParams(location.hash.slice(1)).get('cap');
  let tabCapability = launchCapability;
  try {if (launchCapability) sessionStorage.setItem(capabilityStorageKey, launchCapability); else tabCapability = sessionStorage.getItem(capabilityStorageKey);} catch (_) { /* A blocked store still permits the current launch link. */ }
  const state = {capability: tabCapability, sources: [], checkpoints: [], source: null, checkpoint: null, view: 'landscape', calculation: null, surface: null, search: null, revision: 0, controller: null, searchController: null, sourceRevision: 0, playback: null, saving: false, valid: true, busy: false, searchBusy: false, webgl: null, surfaceRequest: null, loadedSearchGrid: null};
  if (launchCapability) history.replaceState(null, '', location.pathname + location.search);
  const emptyScenario = {spot_shift: 0, iv_shift: 0, time_advance: 0, model: 'raw_trade_volume', exclude_nearest_expiry: false, fallback_dte: .25, risk_free_rate: .045};
  let retainedAssumptions = {fallback_dte: .25, risk_free_rate: .045, minimum_directional_coverage: .5};
  let calculateTimer, toastTimer;
  const formatNumber = (value, digits = 2) => Number.isFinite(Number(value)) && value !== null ? Number(value).toLocaleString(undefined, {maximumFractionDigits: digits}) : '—';
  const money = (value) => {if (!Number.isFinite(value)) return '—'; const absolute = Math.abs(value); const scale = absolute >= 1e9 ? [1e9, 'B'] : absolute >= 1e6 ? [1e6, 'M'] : absolute >= 1e3 ? [1e3, 'K'] : [1, '']; return `${value > 0 ? '+' : value < 0 ? '−' : ''}${(absolute / scale[0]).toFixed(2)}${scale[1]}`;};
  const signed = (value, digits = 6) => `${Number(value) > 0 ? '+' : ''}${formatNumber(Number(value), digits)}`;
  const timeLabel = (value) => {if (!value) return 'No event time'; const date = new Date(value); return Number.isNaN(date.valueOf()) ? String(value) : date.toLocaleTimeString([], {hour: '2-digit', minute: '2-digit', timeZone: 'UTC'}) + ' UTC';};
  function text(selector, value) {$(selector).textContent = value;}
  function status(message, isError = false) {text('#calculation-status', message); $('#calculation-status').classList.toggle('error', isError);}
  function toast(message) {clearTimeout(toastTimer); text('#toast', message); $('#toast').hidden = false; toastTimer = setTimeout(() => {$('#toast').hidden = true;}, 5500);}
  async function api(path, options = {}) {
    if (!state.capability) throw new Error('This local session needs its launch link. Start Wind Tunnel again to open a fresh authenticated window.');
    const headers = {'X-GEX-Capability': state.capability};
    if (options.body !== undefined || options.rawBody !== undefined) headers['Content-Type'] = 'application/json';
    const response = await fetch(`/api/${path}`, {...options, headers, body: options.rawBody !== undefined ? options.rawBody : options.body === undefined ? undefined : JSON.stringify(options.body)});
    if (response.status === 403) {state.capability = null; try {sessionStorage.removeItem(capabilityStorageKey);} catch (_) {} const message = 'This local session has expired or its launch key has changed. Open a fresh Wind Tunnel launch link to continue.'; text('#connection-error', message); $('#connection-error').hidden = false; throw new Error(message);}
    if (!response.ok) {let message = `Local service returned ${response.status}.`; try {const result = await response.json(); message = result.error?.message || message;} catch (_) {} throw new Error(message);}
    return options.blob ? response.blob() : options.text ? response.text() : response.json();
  }
  const post = (path, body, signal) => api(path, {method: 'POST', body, signal});
  function node(tag, content, className) {const element = document.createElement(tag); if (content !== undefined) element.textContent = content; if (className) element.className = className; return element;}
  function toggleBusy() {$('#run-search').disabled = !state.source || !state.valid || state.busy || state.searchBusy; $('#save-scenario').disabled = !state.calculation || !state.valid || state.busy || state.searchBusy; $('#confirm-save').disabled = state.saving; text('#run-search-label', state.searchBusy ? 'Searching tested cases…' : 'Find breaking point');}
  function requestFromControls() {
    const request = {session: state.source, checkpoint: state.checkpoint, ...retainedAssumptions, model: $('#position-model').value, spot_shift: Number($('#spot-number').value), iv_shift: Number($('#iv-number').value), time_advance: Number($('#time-number').value), exclude_nearest_expiry: $('#remove-expiry').checked};
    const valid = ['#spot-number', '#iv-number', '#time-number'].every(selector => $(selector).value !== '' && $(selector).checkValidity());
    state.valid = valid;
    $('#scenario-validation').hidden = valid;
    text('#scenario-validation', valid ? '' : 'Enter values inside the displayed ranges before recalculating.');
    return valid ? request : null;
  }
  function populateScenario(request) {
    retainedAssumptions = {fallback_dte: request.fallback_dte ?? .25, risk_free_rate: request.risk_free_rate ?? .045, minimum_directional_coverage: request.minimum_directional_coverage ?? .5};
    for (const [key, range, number] of [['spot_shift', '#spot-shift', '#spot-number'], ['iv_shift', '#iv-shift', '#iv-number'], ['time_advance', '#time-advance', '#time-number']]) {$(range).value = request[key] ?? 0; $(number).value = request[key] ?? 0;}
    $('#position-model').value = request.model || 'raw_trade_volume'; $('#remove-expiry').checked = Boolean(request.exclude_nearest_expiry);
  }
  function clearSearch() {if (state.searchController) state.searchController.abort(); state.searchController = null; state.searchBusy = false; state.search = null; $('#search-table tbody').replaceChildren(); text('#tested-claim', 'Choose a claim and run a bounded search.'); text('#map-caption', 'A finite grid is a sensitivity test, not a probability or a continuous boundary.'); $('#apply-breaking-case').hidden = true; const box = $('#search-result'); box.replaceChildren(node('p', 'BOUNDED SEARCH', 'eyebrow'), node('h3', 'No current search.'), node('p', 'Run a search for this checkpoint and set of assumptions.')); if (state.view === 'fragility') emptyPlot('#fragility-plot', 'Test a claim across price and IV shifts.', 'Choose the claim and bounds, then find a breaking point.');}
  function scheduleCalculation() {stopPlayback(); clearSearch(); state.revision++; clearTimeout(calculateTimer); state.controller?.abort(); state.calculation = null; state.surface = null; state.busy = false; const request = requestFromControls(); toggleBusy(); if (!request) {status('Invalid scenario inputs', true); text('#scenario-state', 'Inputs need attention'); return;} status('Assumptions changed · recalculating…'); text('#scenario-state', 'Recalculating…'); calculateTimer = setTimeout(() => calculate(), 180);}
  function emptyPlot(selector, title, description = '') {const target = $(selector); if (window.Plotly && target.data) Plotly.purge(target); target.classList.add('plot-empty'); target.replaceChildren(node('strong', title), node('p', description));}
  function chartLayout(extra = {}) {return {paper_bgcolor: 'transparent', plot_bgcolor: 'transparent', font: {family: 'SFMono-Regular, Consolas, monospace', color: colors.text, size: 11}, margin: {l: 55, r: 18, t: 16, b: 55}, showlegend: false, hoverlabel: {bgcolor: '#142333', font: {color: '#f0f4fb', size: 12}}, xaxis: {gridcolor: colors.grid, zerolinecolor: '#4c6278', linecolor: '#40546b', title: {text: 'Strike'}, tickformat: ',.0f'}, yaxis: {gridcolor: colors.grid, zerolinecolor: '#8297ad', title: {text: 'Net GEX (billions)'}}, ...extra};}
  async function draw(selector, traces, layout) {const target = $(selector); if (target.classList.contains('plot-empty')) target.replaceChildren(); target.classList.remove('plot-empty'); if (!window.Plotly) {emptyPlot(selector, 'Chart library unavailable.', 'The local Plotly asset could not be loaded. Values remain available in Compare and source details.'); return;} await Plotly.react(target, traces, layout, {responsive: true, displaylogo: false, displayModeBar: false, scrollZoom: false});}
  function summaryOf(value) {return value?.summary || {};}
  function netOf(value) {return summaryOf(value).total_net_gex ?? null;}
  function wallOf(value) {return summaryOf(value).gamma_wall_strike ?? summaryOf(value).gamma_wall ?? null;}
  function matrixOf(value) {const matrix = value?.matrix; if (!matrix) return {strikes: [], net_gex: []}; return matrix;}
  function stateUsable(value) {return Number.isFinite(netOf(value));}
  function changeDescription(request) {const items = []; if (request.spot_shift) items.push(`${signed(request.spot_shift)} price points`); if (request.iv_shift) items.push(`${signed(request.iv_shift)} volatility points`); if (request.time_advance) items.push(`${formatNumber(request.time_advance)} minutes advanced`); if (request.exclude_nearest_expiry) items.push('nearest expiry removed'); return items.length ? items.join(' · ') : 'No scenario assumptions changed.';}
  function updateFingerprint() {const kind = state.view === 'fragility' && state.search ? 'Search' : state.view === 'landscape' && state.surface ? 'Surface' : 'Scenario'; const report = kind === 'Search' ? state.search : kind === 'Surface' ? state.surface : state.calculation; const fingerprint = report?.result_sha256; text('#source-fingerprint', fingerprint ? `${kind} result ${fingerprint.slice(0, 12)} · ${modelNames[$('#position-model').value]}` : 'Local calculations. No market connection.');}
  function renderCalculation() {
    const report = state.calculation; if (!report) return;
    const base = report.baseline, scenario = report.scenario;
    text('#metric-baseline-net', money(netOf(base))); text('#metric-scenario-net', money(netOf(scenario))); text('#metric-baseline-wall', formatNumber(wallOf(base))); text('#metric-scenario-wall', formatNumber(wallOf(scenario)));
    const changed = changeDescription(report.request || requestFromControls());
    text('#scenario-state', stateUsable(scenario) ? (changed === 'No scenario assumptions changed.' ? 'Original assumptions' : 'Scenario recalculated') : 'Not evaluable');
    text('#spot-effective', `Original price ${formatNumber(base?.spot)}`);
    text('#compare-caption', changed);
    const problems = [base, scenario].filter(value => !stateUsable(value)).map(value => value?.reason || value?.status || 'Selected model is not evaluable.');
    $('#result-notice').hidden = !problems.length; text('#result-notice', [...new Set(problems)].join(' '));
    updateFingerprint();
    renderCompare();
  }
  function renderCompare() {
    if (!state.calculation) return;
    const base = matrixOf(state.calculation.baseline), scenario = matrixOf(state.calculation.scenario);
    const baseValues = base.net_gex || [], scenarioValues = scenario.net_gex || [];
    const all = [...baseValues, ...scenarioValues].filter(Number.isFinite).map(value => value / 1e9);
    const strikes = [...(base.strikes || []), ...(scenario.strikes || [])]; const xPad = strikes.length ? Math.max(1, (Math.max(...strikes) - Math.min(...strikes)) * .06) : 1; const xRange = strikes.length ? [Math.min(...strikes) - xPad, Math.max(...strikes) + xPad] : undefined;
    let low = Math.min(0, ...all), high = Math.max(0, ...all); const pad = Math.max((high - low) * .14, .000001); low -= pad; high += pad;
    for (const [selector, data, color, title] of [['#baseline-plot', base, colors.cyan, 'Original state'], ['#scenario-plot', scenario, colors.amber, 'Recalculated scenario']]) {
      if (!(data.strikes || []).length) {emptyPlot(selector, 'No evaluable exposure', 'Inspect the source and selected quantity model.'); continue;}
      if (state.view === 'compare') draw(selector, [{type: 'bar', x: data.strikes, y: data.net_gex.map(value => value / 1e9), marker: {color}, name: title, hovertemplate: 'Strike %{x:,.2f}<br>Net GEX %{y:.4f}B<extra></extra>'}], chartLayout({xaxis: {...chartLayout().xaxis, range: xRange}, yaxis: {...chartLayout().yaxis, range: [low, high]}, bargap: .2})).catch(chartError);
    }
    const body = $('#comparison-table tbody'); body.replaceChildren();
    const baselineMap = new Map((base.strikes || []).map((strike, index) => [strike, baseValues[index]])); const scenarioMap = new Map((scenario.strikes || []).map((strike, index) => [strike, scenarioValues[index]]));
    [...new Set([...(base.strikes || []), ...(scenario.strikes || [])])].sort((a, b) => a - b).forEach(strike => {const b = stateUsable(state.calculation.baseline) ? baselineMap.get(strike) ?? 0 : null; const s = stateUsable(state.calculation.scenario) ? scenarioMap.get(strike) ?? 0 : null; const row = node('tr'); [formatNumber(strike), money(b), money(s), b === null || s === null ? '—' : money(s - b)].forEach(value => row.append(node('td', value))); body.append(row);});
  }
  function chartError(error) {status(`Chart unavailable: ${error.message}`, true);}
  function supportsWebGL() {if (state.webgl !== null) return state.webgl; try {const canvas = document.createElement('canvas'); const context = canvas.getContext('webgl2') || canvas.getContext('webgl'); state.webgl = Boolean(context); context?.getExtension('WEBGL_lose_context')?.loseContext();} catch (_) {state.webgl = false;} return state.webgl;}
  function surfaceArrays(report) {
    const axes = report.axes || {}; const x = axes.baseline_underlying_prices || []; const sx = axes.scenario_underlying_prices || x; const y = axes.time_advances || []; const sy = axes.scenario_time_advances || y;
    const z = y.map(() => x.map(() => null)), sz = y.map(() => x.map(() => null));
    for (const point of report.points || []) {if (!z[point.time_index] || point.spot_index >= x.length) continue; z[point.time_index][point.spot_index] = Number.isFinite(point.baseline_total_net_gex) ? point.baseline_total_net_gex / 1e9 : null; sz[point.time_index][point.spot_index] = Number.isFinite(point.scenario_total_net_gex) ? point.scenario_total_net_gex / 1e9 : null;}
    return {x, sx, y, sy, z, sz};
  }
  async function renderLandscape() {
    if (!state.surface || state.view !== 'landscape') return;
    const grid = surfaceArrays(state.surface);
    if (!grid.x.length || !grid.y.length || ![...grid.z.flat(), ...grid.sz.flat()].some(Number.isFinite)) {emptyPlot('#landscape-plot', 'No landscape available.', 'This checkpoint cannot be evaluated with the selected model.'); return;}
    let use3d = $('#landscape-render').value === '3d';
    if (use3d && !supportsWebGL()) {$('#landscape-render').value = '2d'; use3d = false; text('#webgl-note', '3D is unavailable in this browser. Showing 2D time slices.');}
    if (!use3d) {
      const traces = [];
      for (const index of [...new Set([0, Math.floor((grid.y.length - 1) / 2), grid.y.length - 1])]) {
        traces.push({type: 'scatter', mode: 'lines', x: grid.x, y: grid.z[index], name: `Original · ${grid.y[index]} min`, line: {color: colors.cyan, width: 2, dash: index === 0 ? 'solid' : 'dot'}, opacity: index === 0 ? 1 : .65, hovertemplate: 'Price %{x:,.2f}<br>Net GEX %{y:.4f}B<extra>%{fullData.name}</extra>'});
        traces.push({type: 'scatter', mode: 'lines', x: grid.sx, y: grid.sz[index], name: `Scenario · ${grid.sy[index]} min`, line: {color: colors.amber, width: 2, dash: 'dash'}, opacity: index === 0 ? 1 : .65, hovertemplate: 'Price %{x:,.2f}<br>Net GEX %{y:.4f}B<extra>%{fullData.name}</extra>'});
      }
      await draw('#landscape-plot', traces, chartLayout({showlegend: true, legend: {orientation: 'h', x: 0, y: -.19, font: {size: 9}}, margin: {l: 60, r: 15, t: 15, b: 95}, xaxis: {...chartLayout().xaxis, title: {text: 'Underlying price'}}}));
      text('#landscape-caption', 'Original and scenario exposure at three sampled times. Dashed lines identify the scenario; hover for exact values.'); return;
    }
    const traces = [];
    const identical = JSON.stringify([grid.x, grid.y, grid.z]) === JSON.stringify([grid.sx, grid.sy, grid.sz]);
    const surfaces = [[grid.x, grid.y, grid.z, colors.cyan, identical ? 'Original and unchanged scenario' : 'Original state', .84]];
    if (!identical) surfaces.push([grid.sx, grid.sy, grid.sz, colors.amber, 'Recalculated scenario', .7]);
    for (const [x, y, z, color, name, opacity] of surfaces) {
      traces.push({type: 'surface', x, y, z, name, colorscale: [[0, color], [1, color]], showscale: false, opacity, lighting: {ambient: .78, diffuse: .55, specular: .15, roughness: .9}, contours: {x: {show: true, color: '#152536', width: 1}, y: {show: true, color: '#152536', width: 1}, z: {show: false}}, hovertemplate: 'Price %{x:,.2f}<br>Time +%{y:.0f} min<br>Net GEX %{z:.4f}B<extra>' + name + '</extra>'});
    }
    const axis = {gridcolor: colors.grid, zerolinecolor: '#4c6278', showbackground: false, color: colors.text, tickfont: {size: 10}};
    try {await draw('#landscape-plot', traces, chartLayout({margin: {l: 0, r: 0, t: 0, b: 0}, scene: {bgcolor: 'transparent', xaxis: {...axis, title: {text: 'Underlying price'}, tickformat: ',.0f'}, yaxis: {...axis, title: {text: 'Time advanced (min)'}}, zaxis: {...axis, title: {text: 'Net GEX (B)'}}, camera: {eye: {x: 1.2, y: -1.4, z: .85}}, aspectratio: {x: 1.65, y: 1, z: .72}}, uirevision: state.source})); $('#landscape-plot').removeAllListeners?.('plotly_webglcontextlost'); $('#landscape-plot').on?.('plotly_webglcontextlost', () => {state.webgl = false; $('#landscape-render').value = '2d'; text('#webgl-note', '3D context lost. Showing 2D time slices.'); renderLandscape().catch(chartError);}); text('#landscape-caption', (identical ? 'Original and scenario coincide; a single cyan surface shows both. ' : '') + 'Drag to rotate. Hover for exact values. The mesh between calculated samples is a visual interpolation.');}
    catch (error) {state.webgl = false; $('#landscape-render').value = '2d'; text('#webgl-note', '3D could not render. Showing 2D time slices.'); await renderLandscape();}
  }
  function linspace(low, high, count) {return Array.from({length: count}, (_, index) => Number((low + (high - low) * index / (count - 1)).toFixed(6)));}
  async function calculate() {
    const request = requestFromControls(); if (!request || !state.source) return;
    const revision = ++state.revision; state.controller?.abort(); const controller = new AbortController(); state.controller = controller; state.surface = null; state.busy = true; toggleBusy(); status('Recalculating from local source…');
    try {
      const report = await post('calculate', request, controller.signal); if (revision !== state.revision) return;
      state.calculation = report; renderCalculation();
      const surfaceRequest = {...request, spot_shifts: linspace(-100, 100, 17), time_advances: linspace(0, 60, 9)}; state.surfaceRequest = surfaceRequest;
      status('Calculating landscape samples…'); const surface = await post('surface', surfaceRequest, controller.signal); if (revision !== state.revision) return; state.surface = surface; updateFingerprint(); await renderLandscape(); status('Calculated locally · source preserved');
    } catch (error) {if (error.name !== 'AbortError' && revision === state.revision) {state.calculation = null; state.surface = null; status(error.message, true); text('#scenario-state', 'Calculation unavailable'); $('#result-notice').hidden = false; text('#result-notice', error.message);}}
    finally {if (revision === state.revision) {state.busy = false; toggleBusy();}}
  }
  function checkpointTime(checkpoint) {return checkpoint?.event_time || checkpoint?.as_of || checkpoint?.timestamp;}
  function setCheckpoint(position) {const checkpoint = state.checkpoints[position]; if (!checkpoint) return; state.checkpoint = checkpoint.index ?? checkpoint.event_index ?? checkpoint.checkpoint ?? position; $('#checkpoint').value = position; text('#checkpoint-label', timeLabel(checkpointTime(checkpoint))); text('#checkpoint-count', `${position + 1} of ${state.checkpoints.length} checkpoints`);}
  async function loadSource(session, desiredCheckpoint = undefined) {
    stopPlayback(); clearTimeout(calculateTimer); state.controller?.abort(); state.revision++; const revision = ++state.sourceRevision; state.source = session; state.calculation = null; state.surface = null; clearSearch(); state.busy = true; toggleBusy(); $('#source').value = session; status('Loading replay checkpoints…');
    const source = state.sources.find(item => (item.name || item.id || item.session) === session); text('#header-source', `${source?.symbol || 'Research'} · Synthetic replay · ${source?.first_as_of?.slice(0, 10) || ''}`);
    for (const option of $('#position-model').options) option.textContent = modelNames[option.value] + (source?.models?.[option.value]?.available_in_source === false ? ' · no source fields' : '');
    try {const result = await api(`checkpoints?session=${encodeURIComponent(session)}`); if (revision !== state.sourceRevision) return; state.checkpoints = result.checkpoints || []; if (!state.checkpoints.length) throw new Error('This source has no evaluable checkpoints. Select another synthetic replay.');
      $('#checkpoint').max = state.checkpoints.length - 1; $('#checkpoint').disabled = false;
      const requestedPosition = state.checkpoints.findIndex((item, index) => (item.index ?? item.event_index ?? item.checkpoint ?? index) === desiredCheckpoint);
      setCheckpoint(requestedPosition >= 0 ? requestedPosition : state.checkpoints.length - 1); text('#checkpoint-start', timeLabel(checkpointTime(state.checkpoints[0]))); text('#checkpoint-end', timeLabel(checkpointTime(state.checkpoints.at(-1)))); await calculate();
    } catch (error) {if (revision === state.sourceRevision) {status(error.message, true); state.busy = false; $('#checkpoint').disabled = true; emptyPlot('#landscape-plot', 'Source unavailable', error.message); toggleBusy();}}
  }
  function stopPlayback() {if (state.playback) clearInterval(state.playback); state.playback = null; $('#play-replay').setAttribute('aria-label', 'Play replay checkpoints'); $('#play-replay').title = 'Play checkpoints'; $('#play-replay').classList.remove('playing'); const image = document.createElement('img'); image.src = '/static/icons/play.svg'; image.alt = ''; $('#play-replay').replaceChildren(image);}
  function playReplay() {if (state.playback) {stopPlayback(); return;} if (!state.checkpoints.length) return; if (Number($('#checkpoint').value) >= state.checkpoints.length - 1) setCheckpoint(0); $('#play-replay').setAttribute('aria-label', 'Pause replay checkpoints'); $('#play-replay').title = 'Pause checkpoints'; $('#play-replay').classList.add('playing'); $('#play-replay').replaceChildren(node('span', 'Pause')); calculate(); state.playback = setInterval(() => {if (state.busy) return; const next = Number($('#checkpoint').value) + 1; if (next >= state.checkpoints.length) {stopPlayback(); return;} clearSearch(); setCheckpoint(next); calculate();}, 1000);}
  function setView(view, focus = false) {state.view = view; for (const tab of $$('.tabs button')) {const active = tab.dataset.view === view; tab.setAttribute('aria-selected', active); tab.tabIndex = active ? 0 : -1; $(`#panel-${tab.dataset.view}`).hidden = !active; if (active && focus) tab.focus();}
    const copy = {landscape: ['Find what changes the structure.', 'Change the assumptions. See how the modeled exposure responds.'], compare: ['Branch a market moment.', 'See exactly which assumption changes the modeled structure.'], fragility: ['How far does the conclusion hold?', 'Test a claim within explicit bounds. Inspect the smallest tested change.']}[view]; text('#view-title', copy[0]); text('#view-description', copy[1]); if (view === 'landscape') renderLandscape().catch(chartError); if (view === 'compare') renderCompare(); if (view === 'fragility') renderMap(); updateFingerprint();}
  function searchRequest() {const request = requestFromControls(); if (!request) return null; if (!$('#search-price').checkValidity() || !$('#search-iv').checkValidity() || !$('#search-price').value || !$('#search-iv').value) {toast('Enter positive price and IV search bounds within the displayed ranges.'); return null;} const count = Number($('#search-samples').value); const loaded = $('#search-samples').value === 'loaded' ? state.loadedSearchGrid : null; const price = Number($('#search-price').value), iv = Number($('#search-iv').value); return {...request, x_axis: 'spot_shift', y_axis: 'iv_shift', x_values: loaded ? loaded.x : linspace(-price, price, count), y_values: loaded ? loaded.y : linspace(-iv, iv, count), claim: $('#claim').value, comparison_model: $('#comparison-model').value};}
  async function runSearch(override) {stopPlayback(); const request = override || searchRequest(); if (!request) return; const revision = state.revision; state.searchController?.abort(); const controller = new AbortController(); state.searchController = controller; state.searchBusy = true; toggleBusy(); setView('fragility'); status('Searching a finite grid of local scenarios…'); $('#apply-breaking-case').hidden = true; $('#search-result').replaceChildren(node('p', 'CALCULATING', 'eyebrow'), node('h3', 'Testing the bounds…'), node('p', 'Each point is a fresh model calculation. No market data is requested.'));
    try {const report = await post('search', request, controller.signal); if (controller.signal.aborted || revision !== state.revision) return; state.search = report; renderMap(); renderSearchResult(); updateFingerprint(); status('Bounded search complete · tested cases only');}
    catch (error) {if (error.name !== 'AbortError') {status(error.message, true); $('#search-result').replaceChildren(node('p', 'SEARCH UNAVAILABLE', 'eyebrow'), node('h3', 'Could not finish.'), node('p', error.message));}}
    finally {if (state.searchController === controller) {state.searchBusy = false; toggleBusy();}}
  }
  function smallestRequest() {const smallest = state.search?.smallest_change; if (!smallest) return null; return smallest.request || {...state.search.request, [state.search.request.x_axis]: smallest.x_value ?? smallest.x, [state.search.request.y_axis]: smallest.y_value ?? smallest.y};}
  function renderSearchResult() {const report = state.search, smallest = report.smallest_change; const box = $('#search-result'); box.replaceChildren(); const labels = {break_found: ['BREAKING CASE FOUND', 'Smallest tested change'], no_break_found: ['NO BREAK FOUND', 'Holds in the tested grid'], not_evaluable: ['NOT EVALUABLE', 'No valid comparison']}; const [eyebrow, heading] = labels[report.outcome] || ['SEARCH COMPLETE', report.outcome]; box.append(node('p', eyebrow, 'eyebrow'), node('h3', heading)); if (smallest) {const request = smallestRequest(); box.append(node('p', `${signed(request.spot_shift)} price pts · ${signed(request.iv_shift)} vol pts · ${formatNumber(request.time_advance)} min`), node('p', 'Smallest normalized distance among tested cases. Untested changes may produce a closer break.'));} else {box.append(node('p', report.outcome === 'no_break_found' ? 'The claim did not change at evaluated points within these bounds. This is not a guarantee between or beyond them.' : 'The selected quantity model or shifted inputs cannot support this claim. Inspect assumptions or choose a different model.'));} $('#apply-breaking-case').hidden = !smallest;}
  function renderMap() {if (state.view !== 'fragility') return; if (!state.search) {emptyPlot('#fragility-plot', 'Test a claim across price and IV shifts.', 'Choose the claim and bounds, then find a breaking point.'); return;} const report = state.search, request = report.request; const cells = report.cells || report.points || [];
    const body = $('#search-table tbody'); body.replaceChildren(); for (const cell of cells) {const row = node('tr'); [signed(cell.x), signed(cell.y), cell.status.replaceAll('_', ' '), formatNumber(cell.summary?.gamma_wall), money(cell.summary?.total_net_gex), cell.reason || '—'].forEach(value => row.append(node('td', value))); body.append(row);} const groups = {unchanged: [], changed: [], not_evaluable: []}; for (const cell of cells) (groups[cell.status] || groups.not_evaluable).push(cell);
    const traces = Object.entries(groups).filter(([, values]) => values.length).map(([key, values]) => ({type: 'scatter', mode: 'markers', x: values.map(cell => cell.x_value ?? cell.x), y: values.map(cell => cell.y_value ?? cell.y), text: values.map(cell => cell.reason || (key === 'changed' ? 'Claim changes at this tested point' : key === 'unchanged' ? 'Claim holds at this tested point' : 'Not evaluable')), name: key === 'changed' ? 'Claim changes' : key === 'unchanged' ? 'Claim holds' : 'Not evaluable', marker: {color: key === 'changed' ? colors.amber : key === 'unchanged' ? colors.cyan : '#566778', symbol: key === 'not_evaluable' ? 'x' : 'square', size: Math.max(9, Math.min(28, 330 / request.x_values.length)), opacity: .8, line: {width: 1, color: '#0b1520'}}, hovertemplate: 'Price shift %{x:+.2f} pts<br>IV shift %{y:+.2f} pts<br>%{text}<extra></extra>'}));
    traces.push({type: 'scatter', mode: 'markers', x: [0], y: [0], name: 'Zero price / IV shift', marker: {color: '#f0f4fb', size: 12, symbol: 'circle-open', line: {width: 2}}, hovertemplate: 'Zero price / IV shift<br>Other selected assumptions remain fixed<extra></extra>'});
    if (report.smallest_change) {const smallest = smallestRequest(); traces.push({type: 'scatter', mode: 'markers', x: [smallest[request.x_axis]], y: [smallest[request.y_axis]], name: 'Smallest tested break', marker: {color: colors.amber, size: 18, symbol: 'diamond-open', line: {width: 3}}, hovertemplate: 'Smallest tested break<br>Price %{x:+.2f}<br>IV %{y:+.2f}<extra></extra>'});}
    text('#tested-claim', `Tested claim: ${$('#claim').selectedOptions[0].textContent}.`); text('#map-caption', `${cells.length} tested cases. Marker colors describe evaluated points only; gaps are not a continuous boundary. Time and expiry treatment remain fixed at your selected settings.`);
    draw('#fragility-plot', traces, chartLayout({xaxis: {...chartLayout().xaxis, title: {text: 'Underlying price shift (points)'}, zeroline: true}, yaxis: {...chartLayout().yaxis, title: {text: 'IV shift (volatility points)'}, zeroline: true}})).catch(chartError);
  }
  function showDialog(selector) {stopPlayback(); $(selector).showModal();}
  function showHelp() {text('#info-title', 'Use the Wind Tunnel'); const body = $('#info-content'); body.replaceChildren(); [['Start with a checkpoint', 'Choose a bundled synthetic replay and move the checkpoint slider. The original state is preserved while each scenario is calculated independently. The local launch session stays available across refreshes in this browser tab.'], ['Stress one assumption at a time', 'Price shifts are underlying points. IV shifts are absolute volatility points: +1 point adds 0.01 to IV. Time advanced reprices the same quantities; it does not forecast trades. Expiry removal excludes contracts from the scenario.'], ['Read the three views', 'Landscape samples price and time. Compare shows strike exposure on matched scales. Fragility Map tests a finite price/IV grid for a specified claim, with other settings held fixed. The smallest tested break is not a mathematical global minimum.'], ['Keep the model distinction', 'Open interest, trade volume, and directionalized volume are distinct quantities. A model without the required source fields is not evaluable. None identifies observed dealer inventory.'], ['Save and reproduce', 'Saved scenarios retain source identities, exact requests and results. Reopening recalculates and verifies the portable receipt. Export downloads that receipt as JSON.'], ['Keyboard and accessible views', 'Use Tab to move between controls, arrow keys inside the view tabs or sliders, and Escape to close a dialog. Number inputs mirror sliders. Switch the landscape to 2D if 3D is unavailable. Compare also includes a table of exact strike values.'], ['Evidence limit', 'Inputs are synthetic and outputs are conditional on the selected model. Predictive validity remains unmeasured. These scenarios do not estimate probabilities or give trade recommendations.']].forEach(([heading, copy]) => body.append(node('h3', heading), node('p', copy))); showDialog('#info-dialog');}
  function showSource() {text('#info-title', 'Source & assumptions'); const body = $('#info-content'); body.replaceChildren(node('p', 'This local session uses packaged synthetic inputs. The calculation receipt identifies the exact checkpoint and model.')); if (!state.calculation) {body.append(node('p', 'Select a source and allow the calculation to complete.'));} else {const r = state.calculation; const list = node('dl'); const fields = [['Replay', state.source], ['Checkpoint', state.checkpoint], ['Quantity model', modelNames[$('#position-model').value]], ['Fallback DTE', `${r.request.fallback_dte} days`], ['Risk-free rate', `${(r.request.risk_free_rate * 100).toFixed(2)}%`], ['Result identity', r.result_sha256 || 'Unavailable']]; for (const [name, value] of fields) list.append(node('dt', name), node('dd', String(value))); body.append(list); body.append(node('h3', 'Calculation provenance'), node('pre', JSON.stringify({source: r.source, checkpoint: r.checkpoint, counts: r.scenario?.counts, reasons: r.scenario?.reason, calculation_fingerprint: r.calculation_fingerprint}, null, 2))); if (r.scenario?.contracts) {const details = node('details'); details.append(node('summary', 'Inspect contributing contract records'), node('pre', JSON.stringify(r.scenario.contracts, null, 2))); body.append(details);}} showDialog('#info-dialog');}
  async function listReceipts() {showDialog('#receipts-dialog'); const list = $('#receipts-list'); list.replaceChildren(node('p', 'Loading local receipts…')); try {const result = await api('receipts'); list.replaceChildren(); if (!result.receipts?.length) {list.append(node('p', 'No saved scenarios yet. Recalculate a scenario, then choose Save scenario.')); return;} for (const receipt of result.receipts) {const row = node('div', undefined, 'receipt-item'); const meta = node('div'); meta.append(node('h3', receipt.name), node('p', `${receipt.kind} · ${receipt.created_at}`)); const actions = node('div', undefined, 'receipt-actions'); const reopen = node('button', 'Reopen'); reopen.type = 'button'; reopen.addEventListener('click', () => reopenReceipt(receipt.id, reopen)); const download = node('button', 'Export JSON'); download.type = 'button'; download.addEventListener('click', () => exportReceipt(receipt.id, download)); actions.append(reopen, download); row.append(meta, actions); list.append(row);}} catch (error) {list.replaceChildren(node('p', error.message, 'validation-message'));}}
  async function exportReceipt(id, button) {button.disabled = true; try {const blob = await api(`receipts/${encodeURIComponent(id)}/export`, {blob: true}); const url = URL.createObjectURL(blob); const link = node('a'); link.href = url; link.download = `gex-wind-tunnel-${id.slice(0, 12)}.json`; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); toast('Portable receipt exported.');} catch (error) {toast(error.message);} finally {button.disabled = false;}}
  async function reopenRequest(kind, request, reproduced = null) {
    if (kind === 'search' && (request.x_axis !== 'spot_shift' || request.y_axis !== 'iv_shift')) throw new Error('This receipt is valid, but its axes are not the price/IV map supported by this view. Use the CLI to inspect that search.');
    populateScenario(request); await loadSource(request.session, request.checkpoint);
    if (!state.calculation) throw new Error('The saved calculation could not be opened. Its receipt is unchanged.');
    if (kind === 'search') {
      $('#claim').value = request.claim; $('#comparison-model').value = request.comparison_model || 'open_interest'; $('#comparison-model-control').hidden = $('#claim').value !== 'model_disagreement';
      const xs = request.x_values, ys = request.y_values;
      $('#search-price').value = Math.max(...xs.map(Math.abs)); $('#search-iv').value = Math.max(...ys.map(Math.abs));
      state.loadedSearchGrid = {x: [...xs], y: [...ys]}; $('#search-samples option[value=loaded]')?.remove(); const loadedOption = node('option', `Loaded · ${xs.length} × ${ys.length} = ${xs.length * ys.length} cases`); loadedOption.value = 'loaded'; $('#search-samples').append(loadedOption); $('#search-samples').value = 'loaded'; text('#loaded-grid-note', `Exact loaded grid: ${xs.length} × ${ys.length} = ${xs.length * ys.length} tested points. Editing bounds creates a new symmetric grid.`); $('#loaded-grid-note').hidden = false;
      text('#bounds-summary', `±${$('#search-price').value} pts · ±${$('#search-iv').value} vol pts`);
      await runSearch(request);
    } else {
      if (kind === 'surface') {state.surface = reproduced || await post('surface', request); state.surfaceRequest = request;}
      setView(kind === 'surface' ? 'landscape' : 'compare');
    }
  }
  async function reopenReceipt(id, button) {button.disabled = true; try {const rawReceipt = await api(`receipts/${encodeURIComponent(id)}`, {text: true}); const receipt = JSON.parse(rawReceipt); const verified = await api('reproduce', {method: 'POST', rawBody: rawReceipt}); if (verified.status !== 'verified') throw new Error('Saved receipt did not reproduce exactly. Its original record is preserved.'); await reopenRequest(receipt.kind, receipt.request, verified.result); $('#receipts-dialog').close(); toast('Saved scenario verified and reopened.');} catch (error) {toast(error.message);} finally {button.disabled = false;}}
  async function importReceipt(event) {
    const file = event.target.files[0]; if (!file) return;
    text('#import-status', 'Verifying the receipt and reproducing its calculation…'); event.target.disabled = true;
    try {
      if (file.size > 4 * 1024 * 1024) throw new Error('Receipt must be a JSON file no larger than 4 MiB.');
      const rawReceipt = await file.text(); let receipt; try {receipt = JSON.parse(rawReceipt);} catch (_) {throw new Error('This file is not a valid JSON receipt.');}
      const result = await api('reproduce', {method: 'POST', rawBody: rawReceipt}); if (result.status !== 'verified') throw new Error('Receipt did not reproduce exactly. The original file was not changed.');
      await reopenRequest(receipt.kind, receipt.request, result.result); $('#receipts-dialog').close(); toast('Imported receipt verified and reopened. Save scenario to keep a local copy.'); text('#import-status', 'Verified and reopened.');
    } catch (error) {text('#import-status', error.message);}
    finally {event.target.disabled = false; event.target.value = '';}
  }
  async function showExamples() {
    text('#info-title', 'Try a synthetic research example'); const body = $('#info-content'); body.replaceChildren(node('p', 'Each example uses bundled inputs and real calculations. Outcomes describe only its tested grid.')); showDialog('#info-dialog');
    try {const response = await api('examples'); for (const example of response.examples || []) {const section = node('section', undefined, 'example-item'); section.append(node('h3', example.title), node('p', example.description)); const button = node('button', 'Open example', 'secondary-button'); button.type = 'button'; button.addEventListener('click', async () => {button.disabled = true; try {await reopenRequest(example.operation, example.request); $('#info-dialog').close(); toast(`${example.title} loaded.`);} catch (error) {toast(error.message);} finally {button.disabled = false;}}); section.append(button); body.append(section);}} catch (error) {body.append(node('p', error.message, 'validation-message'));}
  }
  async function saveReceipt(event) {event.preventDefault(); const name = $('#scenario-name').value.trim(); if (!name) return; const kind = state.view === 'fragility' && state.search ? 'search' : state.view === 'landscape' && state.surface ? 'surface' : 'calculate'; const request = kind === 'search' ? state.search.request : kind === 'surface' ? state.surface.request || state.surfaceRequest : state.calculation.request; state.saving = true; toggleBusy(); $('#save-error').hidden = true; try {await post('receipts', {name, kind, request}); $('#save-dialog').close(); toast('Scenario saved locally. Open Saved scenarios to reopen or export it.');} catch (error) {text('#save-error', error.message); $('#save-error').hidden = false;} finally {state.saving = false; toggleBusy();}}
  function bindEvents() {
    $('#source').addEventListener('change', event => loadSource(event.target.value));
    for (const [range, number] of [['#spot-shift', '#spot-number'], ['#iv-shift', '#iv-number'], ['#time-advance', '#time-number']]) {$(range).addEventListener('input', () => {$(number).value = $(range).value; scheduleCalculation();}); $(number).addEventListener('input', () => {if ($(number).checkValidity() && $(number).value !== '') $(range).value = $(number).value; scheduleCalculation();});}
    $('#position-model').addEventListener('change', scheduleCalculation); $('#remove-expiry').addEventListener('change', scheduleCalculation); $('#scenario-form').addEventListener('submit', event => event.preventDefault());
    $('#reset-scenario').addEventListener('click', () => {populateScenario(emptyScenario); scheduleCalculation();});
    $('#checkpoint').addEventListener('input', event => {stopPlayback(); clearSearch(); setCheckpoint(Number(event.target.value)); state.revision++; state.controller?.abort(); state.calculation = null; state.surface = null; state.busy = true; toggleBusy(); status('Checkpoint changed · recalculating…'); clearTimeout(calculateTimer); calculateTimer = setTimeout(calculate, 160);});
    $('#play-replay').addEventListener('click', playReplay); $('#landscape-render').addEventListener('change', () => renderLandscape().catch(chartError));
    $$('.tabs button').forEach(tab => {tab.addEventListener('click', () => setView(tab.dataset.view)); tab.addEventListener('keydown', event => {const keys = ['ArrowLeft', 'ArrowRight', 'Home', 'End']; if (!keys.includes(event.key)) return; event.preventDefault(); const tabs = $$('.tabs button'); let index = tabs.indexOf(tab); index = event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : (index + (event.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length; setView(tabs[index].dataset.view, true);});});
    $('#claim').addEventListener('change', () => {$('#comparison-model-control').hidden = $('#claim').value !== 'model_disagreement'; clearSearch();}); $('#comparison-model').addEventListener('change', clearSearch);
    ['#search-price', '#search-iv', '#search-samples'].forEach(selector => $(selector).addEventListener('change', () => {if ($('#search-samples').value === 'loaded') $('#search-samples').value = '11'; state.loadedSearchGrid = null; $('#search-samples option[value=loaded]')?.remove(); $('#loaded-grid-note').hidden = true; text('#bounds-summary', `±${$('#search-price').value} pts · ±${$('#search-iv').value} vol pts`); clearSearch();}));
    $('#run-search').addEventListener('click', () => runSearch()); $('#apply-breaking-case').addEventListener('click', () => {const request = smallestRequest(); if (!request) return; populateScenario(request); clearSearch(); setView('compare'); calculate();});
    $('#open-help').addEventListener('click', showHelp); $('#open-examples').addEventListener('click', showExamples); $('#receipt-file').addEventListener('change', importReceipt); $('#source-details').addEventListener('click', showSource); $('#open-receipts').addEventListener('click', listReceipts);
    $('#save-scenario').addEventListener('click', () => {$('#scenario-name').value = `${state.source} · ${state.view}`; $('#save-error').hidden = true; showDialog('#save-dialog'); $('#scenario-name').focus(); $('#scenario-name').select();}); $('#save-form').addEventListener('submit', saveReceipt);
    $$('[data-close]').forEach(button => button.addEventListener('click', () => button.closest('dialog').close()));
    document.addEventListener('keydown', event => {if (event.key === '?' && !['INPUT', 'SELECT', 'TEXTAREA'].includes(document.activeElement.tagName) && !$('dialog[open]')) {event.preventDefault(); showHelp();}});
    let resizeTimer; window.addEventListener('resize', () => {clearTimeout(resizeTimer); resizeTimer = setTimeout(() => {if (window.Plotly) $$('.plot').filter(element => element.data && element.offsetParent).forEach(element => Plotly.Plots.resize(element));}, 150);});
  }
  async function initialize() {bindEvents(); emptyPlot('#landscape-plot', 'Preparing the research workspace…', 'Loading packaged synthetic replay inputs.'); if (!state.capability) {const message = 'This window needs its local launch link. Start Wind Tunnel again to open a fresh session; no data has been sent.'; text('#connection-error', message); $('#connection-error').hidden = false; status('Launch link required', true); emptyPlot('#landscape-plot', 'Open from your local Wind Tunnel launcher.', 'The local session key is kept only in this browser tab. Open a fresh launch link if the tab or server session has ended.'); return;}
    try {const catalog = await api('catalog'); state.sources = catalog.sessions || catalog.sources || []; const select = $('#source'); select.replaceChildren(); for (const source of state.sources) {const option = node('option', source.title || source.label || source.name); option.value = source.name || source.id || source.session; option.disabled = source.status !== 'available'; if (option.disabled) option.textContent += ' · unavailable'; select.append(option);} const preferred = state.sources.find(item => (item.name || item.id) === 'wind-tunnel-lab' && item.status === 'available') || state.sources.find(item => item.status === 'available'); if (!preferred) throw new Error('No supported synthetic replay sources are installed.'); select.disabled = false; await loadSource(preferred.name || preferred.id || preferred.session);}
    catch (error) {text('#connection-error', error.message); $('#connection-error').hidden = false; status('Local service unavailable', true); emptyPlot('#landscape-plot', 'Could not load the research workspace.', error.message);}
  }
  initialize();
})();
